### ISSUE TITLE
longitude and latitude

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/storm_surge#13]
The longitude and latitude as well as associated storm surge in meters currently look like a weird math equation. Check with the actual researchers, but shouldn't it rather be something like:

(-42,5° /170°): -0.0878437847m

**Comment by neon-ninja** [comment]
how's this? https://github.com/UoA-eResearch/storm_surge/commit/33afcda049602147b78e70be30a10a8422e862cc

**Comment by neon-ninja** [comment]
Also, these are decimal degrees (https://en.wikipedia.org/wiki/Decimal_degrees), not hours/minutes
