### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/storm_surge#29]
The title position and lack of alignment look weird now. If you do want it on the left-hand side, make it the same width as the export panel.

**Comment by neon-ninja** [comment]
Sure, how's this? https://github.com/UoA-eResearch/storm_surge/commit/81f15bcb755230f95743d832d5212be2ef65d612

**Comment by neon-ninja** [comment]
https://rawgit.com/UoA-eResearch/storm_surge/81f15bcb755230f95743d832d5212be2ef65d612/index.html
