### ISSUE TITLE
Timeseries download range & model

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/storm_surge#8]
The timeseries download range is an interactive component whereas the model is a label. Both have the same visual look. Make them distinct from each other. 

Also ensure that the timeseries download range has handles that suggest to the user that the time range is adjustable.

**Comment by neon-ninja** [comment]
how's this? https://github.com/UoA-eResearch/storm_surge/commit/f717a36af1474f155fe75eb34ff10590cf049aa0

**Comment by DorisAtCeR** [comment]
Those arrows are too small. I can only make out that they are arrows and not dirt from 20cm distance. I had one person try it out and they did not notice the arrows either. They need to be at least 4 times as big I would think. Have a look at the Devonport visualisation. I like the red pin for showing the current line which indicates that it is fixed. The water drop sticks out and invites the user to play with it. Maybe you can make round little handle objects on each side? Like little balls or peas? Two yellow ones for the range. An then also add a blue ball to the blue line that can be slid around.

**Comment by neon-ninja** [comment]
Not sure which icons to use here - take a look at 
https://rawgit.com/UoA-eResearch/storm_surge/7d6db633ec281a6e33e3a3abffb954a0bc89e55f/ (standard play/forward/back icons)
vs 
https://rawgit.com/UoA-eResearch/storm_surge/1b1088477fe4d5812163dbc4d7d41295fa9602f6/ (round variants)
- which do you prefer of the two?

**Comment by DorisAtCeR** [comment]
Both solutions have a better usability than the previous solution. However, visually I thought more of an object that matches the 3D style of the red pin. Just to make it more appealing and professionally looking.

**Comment by neon-ninja** [comment]
How's this? https://github.com/UoA-eResearch/storm_surge/commit/8436660293e73020fd086ff1fd42c54a2128ec45
