### ISSUE TITLE
Grouping of interactive controls and info labels

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/storm_surge#9]
You are mixing interactive controls and info labels. This needs looking at. Think about what the user wants to achieve and aim at grouping things together (not for point 0) that belong to one goal, e.g. the user wants to...

0) Look at map and understand what they are seeing (legend, map title, control group titles, clear visual cues as to which controls are interactive and which are informative, see the points in the default size to make it easier for the user to explore the tooltip data that is linked to each data point)
1) load/choose a model
2a) adjust view options of map (zoom)
2b) adjust view options in regards to time
3a) select data/unselect data for export (includes feedback as to what is selected)
3b) export/download data 

For each of those groups don't forget to include a heading and a short instruction, e.g. "Select data points to download:" could accompany the polygon/rectangle/edit layers/delete layers group.

**Comment by neon-ninja** [comment]
How's this? https://github.com/UoA-eResearch/storm_surge/commit/f4ae227c833d47bf623335491c2df079163e7bbb
